server:
  port: 8081
  contextPath: /di-basic
  maxHttpPostSize: 51200000
logging:
  file: log\di-basic.log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic?useSSL=false&serverTimezone=UTC
    username: root
    password: 654321
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: basic
#    password: 123456
#
    druid:
      min-idle: 5
      max-active: 15
      initial-size: 2
      min-evictable-idle-time-millis: 300000
      max-wait: 60000
  freemarker:
    enabled: true
    template-loader-path: classpath:templates/
    request-context-attribute: req
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    cache: true
    suffix: .html
mybatis:
  mapper-locations: classpath*:com/dreamer/basic/**/mapping/*.xml
  dialect: org.apache.ibatis.dialect.OracleDialect
  bbase-package: com.dreamer.basic.**.dao
  aliases-package: com.dreamer.basic.**.entity,com.dreamer.basic.**.data
  underscore-to-camel-case: true
############################# 分割线  #############################################



